import fs from 'fs';
import path from 'path';

import { notFound } from 'next/navigation';

import { Breadcrumb } from '@/components/Breadcrumb';
import { excali } from '@/fonts';
import { BASE_URL } from '@/lib/constants';
import { getAllPosts } from '@/lib/posts';

interface BlogPostMetadata {
  title: string;
  date: string;
  description: string;
  video?: {
    url: string;
    title: string;
    thumbnail?: string;
  };
}

// Calculate reading time (average reading speed: 200 words per minute)
function calculateReadingTime(content: string): number {
  const wordsPerMinute = 200;
  // Remove MDX/JSX syntax, code blocks, and special characters for accurate word count
  const text = content
    .replace(/```[\s\S]*?```/g, '') // Remove code blocks
    .replace(/<[^>]*>/g, '') // Remove HTML/JSX tags
    .replace(/[#*_~`]/g, '') // Remove markdown formatting
    .trim();

  const words = text.split(/\s+/).filter((word) => word.length > 0).length;
  const minutes = Math.ceil(words / wordsPerMinute);
  return minutes;
}

async function getPost(slug: string) {
  try {
    const post = await import(`@/app/blog/posts/${slug}.mdx`);
    const filePath = path.join(
      process.cwd(),
      'src/app/blog/posts',
      `${slug}.mdx`
    );
    const fileContent = fs.readFileSync(filePath, 'utf-8');

    return {
      content: post.default,
      metadata: post.metadata as BlogPostMetadata,
      readingTime: calculateReadingTime(fileContent),
    };
  } catch (_e) {
    return null;
  }
}

// Generate static params for all blog posts at build time
export async function generateStaticParams() {
  const posts = await getAllPosts();
  return posts.map((post) => ({
    slug: post.slug,
  }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const post = await getPost(slug);

  if (!post) {
    return {
      title: 'Post Not Found',
    };
  }

  return {
    title: `${post.metadata.title} | Rand Guy`,
    description: post.metadata.description,
    alternates: {
      canonical: `/blog/${slug}`,
    },
    openGraph: {
      title: post.metadata.title,
      description: post.metadata.description,
      type: 'article',
      publishedTime: post.metadata.date,
      authors: ['Rand Guy'],
      url: `/blog/${slug}`,
      // Dynamic OG image will be automatically generated by opengraph-image.tsx
    },
    twitter: {
      card: 'summary_large_image',
      title: post.metadata.title,
      description: post.metadata.description,
      // Dynamic OG image will be automatically used
    },
  };
}

export default async function BlogPost({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const post = await getPost(slug);

  if (!post) {
    notFound();
  }

  const Content = post.content;

  // Extract video ID from URL for structured data
  function extractVideoId(url: string): string | null {
    const shortsMatch = url.match(/shorts\/([a-zA-Z0-9_-]+)/);
    if (shortsMatch) return shortsMatch[1];
    const regularMatch = url.match(
      /(?:youtube\.com\/watch\?v=|youtu\.be\/)([a-zA-Z0-9_-]+)/
    );
    if (regularMatch) return regularMatch[1];
    return null;
  }

  // Format date to ISO 8601 with timezone (SAST = UTC+2)
  // Convert date string (YYYY-MM-DD) to full ISO 8601 datetime
  function formatISODateTime(dateString: string): string {
    const date = new Date(dateString);
    // Set to SAST timezone (UTC+2) - use noon to avoid timezone conversion issues
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    // Return in ISO 8601 format with timezone offset for SAST (UTC+2)
    return `${year}-${month}-${day}T12:00:00+02:00`;
  }

  // Structured data for SEO
  const blogPostData: any = {
    '@context': 'https://schema.org',
    '@type': 'BlogPosting',
    headline: post.metadata.title,
    description: post.metadata.description,
    datePublished: formatISODateTime(post.metadata.date),
    author: {
      '@type': 'Person',
      name: 'Rand Guy',
    },
  };

  // Add video structured data if video exists
  if (post.metadata.video) {
    const videoId = extractVideoId(post.metadata.video.url);
    if (videoId) {
      blogPostData.video = {
        '@type': 'VideoObject',
        name: post.metadata.video.title,
        description: post.metadata.description,
        thumbnailUrl:
          post.metadata.video.thumbnail ||
          `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg`,
        contentUrl: `https://www.youtube.com/watch?v=${videoId}`,
        embedUrl: `https://www.youtube.com/embed/${videoId}`,
      };
    }
  }

  const breadcrumbData = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      {
        '@type': 'ListItem',
        position: 1,
        name: 'Home',
        item: BASE_URL,
      },
      {
        '@type': 'ListItem',
        position: 2,
        name: 'Blog',
        item: `${BASE_URL}/blog`,
      },
      {
        '@type': 'ListItem',
        position: 3,
        name: post.metadata.title,
        item: `${BASE_URL}/blog/${slug}`,
      },
    ],
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(blogPostData) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbData) }}
      />
      <article className="w-full max-w-3xl p-8">
        <Breadcrumb
          items={[
            { name: 'Home', href: '/' },
            { name: 'Blog', href: '/blog' },
            { name: post.metadata.title },
          ]}
        />

        <header className="mb-8 border-b border-gray-200 pb-6">
          <h1
            className={`${excali.className} mb-3 text-4xl font-bold text-gray-900`}
          >
            {post.metadata.title}
          </h1>
          <div className="flex items-center gap-3 text-gray-600">
            <time dateTime={post.metadata.date}>
              {new Date(post.metadata.date).toLocaleDateString('en-ZA', {
                year: 'numeric',
                month: 'long',
                day: 'numeric',
              })}
            </time>
            <span className="text-gray-300">•</span>
            <span>{post.readingTime} min read</span>
          </div>
        </header>

        <div className="prose prose-lg max-w-none">
          <Content />
        </div>
      </article>
    </>
  );
}
