import Image from 'next/image';

import { BlogPostCard } from '@/components/BlogPostCard';
import { Button } from '@/components/Button';
import { excali } from '@/fonts';
import { BASE_URL } from '@/lib/constants';
import { getAllPosts } from '@/lib/posts';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Rand Guy | South African Personal Finance & Investment Guide',
  description:
    'Learn about personal finance, investing, TFSAs, ETFs, and building wealth in South Africa. Free financial calculators, tax guides, and investment advice for South Africans.',
  alternates: {
    canonical: '/',
  },
  openGraph: {
    title: 'Rand Guy | South African Personal Finance & Investment Guide',
    description:
      'Learn about personal finance, investing, TFSAs, ETFs, and building wealth in South Africa. Free financial calculators and investment advice.',
    type: 'website',
    url: '/',
    siteName: 'Rand Guy',
    // Image will be automatically generated by opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Rand Guy | South African Personal Finance',
    description:
      'Learn about personal finance, investing, TFSAs, ETFs, and building wealth in South Africa.',
    // Image will be automatically generated by opengraph-image.tsx
  },
};

export default async function Home() {
  const posts = await getAllPosts();

  const websiteSchema = {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: 'Rand Guy',
    description:
      'South African personal finance and investment guide. Learn about investing, TFSAs, ETFs, and building wealth.',
    url: BASE_URL,
    inLanguage: 'en-ZA',
    potentialAction: {
      '@type': 'SearchAction',
      target: {
        '@type': 'EntryPoint',
        urlTemplate: `${BASE_URL}/blog?q={search_term_string}`,
      },
      'query-input': 'required name=search_term_string',
    },
  };

  const organizationSchema = {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Rand Guy',
    description: 'South African Personal Finance & Investment Guide',
    url: BASE_URL,
    logo: `${BASE_URL}/RandGuyLogo.png`,
    sameAs: [],
  };

  const blogPostsSchema = {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    itemListElement: posts.slice(0, 5).map((post, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      item: {
        '@type': 'BlogPosting',
        headline: post.title,
        description: post.description,
        datePublished: post.date,
        url: `${BASE_URL}/blog/${post.slug}`,
        author: {
          '@type': 'Person',
          name: 'Rand Guy',
        },
      },
    })),
  };

  const siteNavigationSchema = {
    '@context': 'https://schema.org',
    '@type': 'SiteNavigationElement',
    name: 'Main Navigation',
    url: BASE_URL,
    hasPart: [
      {
        '@type': 'WebPage',
        name: 'Home',
        url: BASE_URL,
        description:
          'South African personal finance and investment advice, calculators, and guides',
      },
      {
        '@type': 'WebPage',
        name: 'Calculators',
        url: `${BASE_URL}/calculators`,
        description:
          'Free financial calculators for South Africans - income tax, UIF, and more',
      },
      {
        '@type': 'WebPage',
        name: 'Historical Data',
        url: `${BASE_URL}/data`,
        description:
          'Historical financial data visualizations for South Africa',
      },
      {
        '@type': 'WebPage',
        name: 'Blog',
        url: `${BASE_URL}/blog`,
        description:
          'Personal finance articles and investment guides for South Africans',
      },
      {
        '@type': 'WebPage',
        name: 'Income Tax Calculator',
        url: `${BASE_URL}/calculators/income-tax`,
        description:
          'Calculate your South African income tax with UIF and age-based rebates',
      },
      {
        '@type': 'WebPage',
        name: 'Home Loan Calculator',
        url: `${BASE_URL}/calculators/home-loan`,
        description:
          'Calculate your home loan repayments and total interest for property purchases',
      },
      {
        '@type': 'WebPage',
        name: 'Loan-to-Value Calculator',
        url: `${BASE_URL}/calculators/ltv`,
        description:
          'Calculate your LTV ratio and understand your equity position for property financing',
      },
      {
        '@type': 'WebPage',
        name: 'TFSA Calculator',
        url: `${BASE_URL}/calculators/tfsa`,
        description:
          'Calculate how long to max out your Tax-Free Savings Account',
      },
    ],
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(blogPostsSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(siteNavigationSchema),
        }}
      />

      {/* Hero Section */}
      <div
        className="w-full px-8 pt-40 pb-32"
        style={{
          background: 'linear-gradient(135deg, #fef3c7 0%, #fde68a 100%)',
        }}
      >
        <div className="mb-12 text-center">
          <Image
            src="/RandGuyLogo.png"
            alt="Rand Guy - South African Personal Finance"
            width={80}
            height={80}
            className="mx-auto mb-4"
          />
          <h1 className={`${excali.className} mb-2 text-4xl`}>
            South African Personal Finance Made Simple
          </h1>
          <p className="mb-6 text-lg text-gray-700">
            Learn how to invest, use TFSAs, buy ETFs, and build wealth in South
            Africa
          </p>
        </div>
      </div>

      {/* Features Section */}
      <div className="w-full bg-gray-50 px-8 py-16">
        <div className="mx-auto max-w-3xl">
          <section>
            <div className="mb-8 grid gap-8 md:grid-cols-2">
              <div className="flex flex-col rounded-lg border border-gray-200 bg-white p-8 text-center transition-all hover:border-yellow-400 hover:shadow-lg">
                <div className="mb-4 text-4xl">🧮</div>
                <h2 className={`${excali.className} mb-3 text-2xl font-bold`}>
                  Financial Calculators
                </h2>
                <p className="mb-6 flex-grow leading-relaxed text-gray-700">
                  Calculate your <strong>income tax</strong>,{' '}
                  <strong>UIF</strong>, and more with these SA-specific tools
                </p>
                <Button href="/calculators">Explore Calculators</Button>
              </div>

              <div className="flex flex-col rounded-lg border border-gray-200 bg-white p-8 text-center transition-all hover:border-yellow-400 hover:shadow-lg">
                <div className="mb-4 text-4xl">📊</div>
                <h2 className={`${excali.className} mb-3 text-2xl font-bold`}>
                  Historical Data & Trends
                </h2>
                <p className="mb-6 flex-grow leading-relaxed text-gray-700">
                  Check out <strong>prime rates</strong>,{' '}
                  <strong>tax brackets</strong>, and how SA finances have
                  evolved
                </p>
                <Button href="/data">View Data</Button>
              </div>
            </div>

            <div className="flex flex-col rounded-lg border border-gray-200 bg-white p-8 text-center transition-all hover:border-yellow-400 hover:shadow-lg">
              <div className="mb-4 text-4xl">📚</div>
              <h2 className={`${excali.className} mb-3 text-2xl font-bold`}>
                Investment Guides & Tips
              </h2>
              <p className="mb-6 flex-grow leading-relaxed text-gray-700">
                Learn how <strong>TFSAs</strong> work, what{' '}
                <strong>ETFs</strong> are, and how to build wealth in South
                Africa
              </p>
              <Button href="/blog">Read Guides</Button>
            </div>
          </section>
        </div>
      </div>

      {/* Latest Blog Posts Section */}
      <div className="w-full px-8 py-16">
        <div className="mx-auto max-w-3xl">
          <section>
            <h2 className={`${excali.className} mb-8 text-center text-3xl`}>
              Latest Posts
            </h2>
            <div className="mb-8 flex flex-col gap-6">
              {posts.map((post) => (
                <BlogPostCard key={post.slug} post={post} />
              ))}
            </div>
            <div className="text-center">
              <Button href="/blog">View All Posts</Button>
            </div>
          </section>
        </div>
      </div>
    </>
  );
}
